export const actionCourseTypes = {
  SET_COURSE_LIST: "SET_COURSE_LIST",
  SET_COURSE_CATEGORIES: "SET_COURSE_CATEGORIES",
  SET_COURSE_SEARCHED: "SET_COURSE_SEARCHED",
};

export const LIST_COURSES = "listCourses";