export const actionCourseTypes = {
  SET_COURSE_LIST: "SET_COURSE_LIST",
  SET_COURSE_CATEGORIES: "SET_COURSE_CATEGORIES",
  SET_COURSE_SEARCHED: "SET_COURSE_SEARCHED",
  SET_COURSE_SEARCHED_NO_RESULT: "SET_COURSE_SEARCHED_NO_RESULT",
  SET_COURSE_BY_CATEGORIES: "SET_COURSE_BY_CATEGORIES",
};

export const LIST_COURSES = "listCourses";
