export const SIGN_IN_ACTION = "SIGN_IN_ACTION";
export const SIGN_UP_ACTION = "SIGN_UP_ACTION";
export const UPDATE_INFOR_ACTION = "UPDATE_INFOR_ACTION";
export const GET_INFOR_USER = "GET_INFOR_USER";
export const INFO_USER = "inforUser";
export const UPDATE_COURSE_USER_REGISTED = "UPDATE_COURSE_USER_REGISTED";
export const UPDATE_COURSE_USER_REVERSED = "UPDATE_COURSE_USER_REVERSED";